# Generated by Django 2.2.2 on 2019-06-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='rep_group',
        ),
        migrations.AddField(
            model_name='workout',
            name='set',
            field=models.ManyToManyField(blank=True, to='workout.Set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.ManyToManyField(blank=True, to='workout.Rep'),
        ),
    ]
